/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LexminFooter {
    }
}
declare global {
    interface HTMLLexminFooterElement extends Components.LexminFooter, HTMLStencilElement {
    }
    var HTMLLexminFooterElement: {
        prototype: HTMLLexminFooterElement;
        new (): HTMLLexminFooterElement;
    };
    interface HTMLElementTagNameMap {
        "lexmin-footer": HTMLLexminFooterElement;
    }
}
declare namespace LocalJSX {
    interface LexminFooter {
    }
    interface IntrinsicElements {
        "lexmin-footer": LexminFooter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lexmin-footer": LocalJSX.LexminFooter & JSXBase.HTMLAttributes<HTMLLexminFooterElement>;
        }
    }
}
