/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LexminFooter {
    }
    interface LexminHeader {
        /**
          * 头部标题 一般是站点或页面标题
         */
        "title": string;
    }
}
declare global {
    interface HTMLLexminFooterElement extends Components.LexminFooter, HTMLStencilElement {
    }
    var HTMLLexminFooterElement: {
        prototype: HTMLLexminFooterElement;
        new (): HTMLLexminFooterElement;
    };
    interface HTMLLexminHeaderElement extends Components.LexminHeader, HTMLStencilElement {
    }
    var HTMLLexminHeaderElement: {
        prototype: HTMLLexminHeaderElement;
        new (): HTMLLexminHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "lexmin-footer": HTMLLexminFooterElement;
        "lexmin-header": HTMLLexminHeaderElement;
    }
}
declare namespace LocalJSX {
    interface LexminFooter {
    }
    interface LexminHeader {
        /**
          * 头部标题 一般是站点或页面标题
         */
        "title"?: string;
    }
    interface IntrinsicElements {
        "lexmin-footer": LexminFooter;
        "lexmin-header": LexminHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lexmin-footer": LocalJSX.LexminFooter & JSXBase.HTMLAttributes<HTMLLexminFooterElement>;
            "lexmin-header": LocalJSX.LexminHeader & JSXBase.HTMLAttributes<HTMLLexminHeaderElement>;
        }
    }
}
